* speed emacs
** After I got used to emacs , I found all the popular emacs configurations work slow on Windows. Yet Windows is my main work platform, so I want to find a set of useful packages which is still fast on Windows.
** How to instll
- 1. backup your .emacs.d
- 2. git clone https://github.com/GreyZhang/speed_emacs ~/.emacs.d
- 3. run you emacs and wait for installation  compelete.
** Package list:
*** emacs
- This is not a package, but emacs itself.
 I add this beacause there are still some configuration just for pure emacs.
- Better support for Chinese word format.
- explicitly set the prefered coding systems to avoid annoying prompt from emacs (especially on Microsoft Windows).

*** dired-mode
F5 -> the hot key for dired-jump

Add revert function to dired-mode hook so the files displayed in dired buffer can be refreshed automatically.

*** evil
- This package is just make emacs act as vim.
- key bindings
C-u -> ued for vim scroll up.

C-] -> jump to tag at point.

C-o -> jump backword.

*** +smex+
- +Smex is a M-x enhancement for Emacs. Built on top of Ido, it provides a convenient interface to your recently and most frequently used commands. And to all the other commands, too.+
- +Refer to: [[https://github.com/nonsequitur/smex][smex]]+
- +key bindings+
+M-x -> run smex+

*** recentf mode
- Use "SPC fr" hot key to invoke recent opend files.
- After recent opened files list is opened, n/p can be used to navigate the list.

*** evil-leader
- This package support some function like the leader key in Vim.
- Refer to: [[https://github.com/cofi/evil-leader][evil-leader]]
- Key bindings(input leader-key first, SPC is my leader-key)
- ff -> find file
- fj -> dired-jump
- fr -> recent opened files
- <SPC> -> sounsel-M-x  ;; this can be used to replace M-x which is just like spacemacs.
- pf -> find file in project
- jj -> jump to file at point(use find-file-in-project-at-point)
- pg -> jump to tag defination.
- ca -> search files with ag.
- oit -> insert org-mode structure template
- oas -> org-archive-subtree
- ss -> swiper ;; same as sapcemacs
*** AutoPairs
Use electric-pair-mode which already supported by emacs 24.4+.

*** which-key
- This package can give us some indication for key bindings.
- Refer to: [[https://github.com/justbur/emacs-which-key][which-key]]

*** company
A good package which can help us auto complete anything.
- Refer to: [[https://company-mode.github.io/][Company]]

*** find-file-in-project
Project files management which can be used to replace some functions in projectile.
- Refer to: [[https://github.com/technomancy/find-file-in-project][find-file-in-project]]

*** counsel
This package is the base of counsel-etags, also provide some more enhancement. The new function for M-x is used counsel-M-x of this package instead.

*** counsel-etags
Create tags and navigation management.
- Refer to: [[https://github.com/redguardtoo/counsel-etags][counsel-etags]]

*** org-pomodoro
A package used for Tomato working method (tomato clock time management)
- Refer to: [[https://github.com/marcinkoziej/org-pomodoro][org-pomodoro]]

*** org-mode
org-startup-truncated is set as nil by default.

