* speed emacs
** After I got used to emacs , I found all the popular emacs configurations work slow on Windows. Yet Windows is my main work platform, so I want to find a set of useful packages which is still fast on Windows.
** How to instll
- 1. backup your .emacs.d
- 2. git clone https://github.com/GreyZhang/speed_emacs ~/.emacs.d
- 3. run you emacs and wait for installation  compelete.
** Package list:
*** emacs
- This is not a package, but emacs itself.
 I add this beacause there are still some configuration just for pure emacs.

F5 -> the hot key for dired-jump

*** evil
- This package is just make emacs act as vim.
- key bindings
C-u -> ued for vim scroll up.

C-] -> jump to tag at point.

C-o -> jump backword.

*** smex
- Smex is a M-x enhancement for Emacs. Built on top of Ido, it provides a convenient interface to your recently and most frequently used commands. And to all the other commands, too.
- Refer to: https://github.com/nonsequitur/smex
- key bindings
M-x -> run smex

*** recentf mode
- Use "SPC fr" hot key to invoke recent opend files.
- After recent opened files list is opened, n/p can be used to navigate the list.

*** evil-leader
- This package support some function like the leader key in Vim.
- Refer to: https://github.com/cofi/evil-leader
- Key bindings(input leader-key first, SPC is my leader-key)
1. ff -> find file
2. fj -> dired-jump
3. fr -> recent opened files
   
*** autopaire
Use autopair to finish some auto competion about brakets.

*** which-key
- This package can give us some indication for key bindings.
- Refer to: https://github.com/justbur/emacs-which-key/tree/8b49ae978cceca65967f3544c236f32964ddbed0

